AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to create a simple S3 bucket.'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'devops-demo-bucket-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Value: !Ref MyS3Bucket
    Description: Name of the created S3 bucket.
